name: Deploy

on:
  push:
    branches:
      - master
jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
  configure-aws-credentials:
    runs-on: ubuntu-latest
    needs: checkout
    steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1
  build:
    runs-on: ubuntu-latest
    needs: configure-aws-credentials
    steps:
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'
      - run: npm ci
      - run: npm run build
  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to S3
        run: aws s3 sync ./dist/ s3://mtj-worldcup-frontend-oiuo2lkj --delete
  invalidate-cloudfront:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Invalidate Cloudfront
        run: |
          aws cloudfront create-invalidation \
          --distribution-id ${{ vars.CLOUDFRONT_DISTRIBUTION }} \
          --paths "/*"
